apiVersion: v1
kind: ConfigMap
metadata:
  name: log-config
data:
  PROCESS_NAME: "SuperLogger"
---
apiVersion: v1
kind: Secret
metadata:
  name: log-secret
type: Opaque
stringData:
  API_KEY: "secret123"
