apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-stress-test
  labels:
    app: memory-stress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-stress-test
  template:
    metadata:
      labels:
        app: memory-stress-test
    spec:
      containers:
      - name: memory-grabber
        image: ghcr.io/clevercloud/test-pod-memory-grabber:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi